=== ngupta40/Assignment4/Assignment4QuestionsAndOutput/Persons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">
  <xsd:simpleType name="CategoryEnum">
    <xsd:restriction base="xsd:normalizedString">
      <xsd:enumeration value="Friend"/>
      <xsd:enumeration value="Family"/>
      <xsd:enumeration value="Work"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="EncryptionEnum">
    <xsd:restriction base="xsd:normalizedString">
      <xsd:enumeration value="Yes"/>
      <xsd:enumeration value="No"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:element name="Persons">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded">
        <xsd:element name="Person" minOccurs="1" maxOccurs="unbounded" >
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Name" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="First" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                    <xsd:element name="Last" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                  </xsd:sequence>   
              </xsd:complexType>
              </xsd:element>
              <xsd:element name="Credential" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Id" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                    <xsd:element name="Password" minOccurs="1" maxOccurs="1">
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base="xsd:string">
                            <xsd:attribute name="Encryption" type="EncryptionEnum" use="required"/>
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="Phone" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Work" type ="xsd:integer" minOccurs="1" maxOccurs="1"/>
                    <xsd:element name="Cell" minOccurs="1" maxOccurs="1">
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base="xsd:integer">
                            <xsd:attribute name="Provider" type ="xsd:string" use="optional"/>
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="Category" type="CategoryEnum" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== ngupta40/Assignment4/Assignment4QuestionsAndOutput/Persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Person.xsl"?>
<!--Sample XML file generated by XMLSpy v2017 rel. 3 sp1 (http://www.altova.com)-->
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Persons.xsd">
	<Person>
		<Name>
			<First>Nitesh</First>
			<Last>Gupta</Last>
		</Name>
		<Credential>
			<Id>ngupta</Id>
			<Password Encryption="Yes">pass1</Password>
		</Credential>
		<Phone>
			<Work>4804103525</Work>
			<Cell Provider="T-Mobile">4804103525</Cell>
		</Phone>
		<Category>Friend</Category>
	</Person>
	<Person>
		<Name>
			<First>Krishna</First>
			<Last>Gupta</Last>
		</Name>
		<Credential>
			<Id>kkgupta</Id>
			<Password Encryption="No">pass2</Password>
		</Credential>
		<Phone>
			<Work>9415145571</Work>
			<Cell Provider="BSNL">9415145571</Cell>
		</Phone>
		<Category>Family</Category>
	</Person>
	<Person>
		<Name>
			<First>Sandhya</First>
			<Last>Gupta</Last>
		</Name>
		<Credential>
			<Id>sgupta</Id>
			<Password Encryption="Yes">pass3</Password>
		</Credential>
		<Phone>
			<Work>9839194457</Work>
			<Cell Provider="VODAFONE">9839194457</Cell>
		</Phone>
		<Category>Work</Category>
	</Person>
	<Person>
		<Name>
			<First>Nitisha</First>
			<Last>Gupta</Last>
		</Name>
		<Credential>
			<Id>nitgup</Id>
			<Password Encryption="No">pass4</Password>
		</Credential>
		<Phone>
			<Work>8447154306</Work>
			<Cell Provider="AIRTEL">8447154306</Cell>
		</Phone>
		<Category>Friend</Category>
	</Person>
	<Person>
		<Name>
			<First>Sahil</First>
			<Last>Garg</Last>
		</Name>
		<Credential>
			<Id>sgarg</Id>
			<Password Encryption="Yes">pass5</Password>
		</Credential>
		<Phone>
			<Work>8095350192</Work>
			<Cell Provider="Idea">8095350192</Cell>
		</Phone>
		<Category>Family</Category>
	</Person>
	<Person>
		<Name>
			<First>Siddhant</First>
			<Last>Agarwal</Last>
		</Name>
		<Credential>
			<Id>sagarwal</Id>
			<Password Encryption="No">pass6</Password>
		</Credential>
		<Phone>
			<Work>9566813430</Work>
			<Cell>9566813430</Cell>
		</Phone>
		<Category>Work</Category>
	</Person>
	<Person>
		<Name>
			<First>Apoorva</First>
			<Last>Singhal</Last>
		</Name>
		<Credential>
			<Id>asinghal</Id>
			<Password Encryption="Yes">pass7</Password>
		</Credential>
		<Phone>
			<Work>8431222151</Work>
			<Cell>8431222151</Cell>
		</Phone>
		<Category>Friend</Category>
	</Person>
	<Person>
		<Name>
			<First>Pulkit</First>
			<Last>Jain</Last>
		</Name>
		<Credential>
			<Id>pjain</Id>
			<Password Encryption="No">pass8</Password>
		</Credential>
		<Phone>
			<Work>991309450</Work>
			<Cell Provider="VODAFONE">991309450</Cell>
		</Phone>
		<Category>Family</Category>
	</Person>
	<Person>
		<Name>
			<First>Gaurav</First>
			<Last>Shad</Last>
		</Name>
		<Credential>
			<Id>gshad</Id>
			<Password Encryption="Yes">pass9</Password>
		</Credential>
		<Phone>
			<Work>4804103526</Work>
			<Cell Provider="T-Mobile">4804103526</Cell>
		</Phone>
		<Category>Work</Category>
	</Person>
	<Person>
		<Name>
			<First>Sumit</First>
			<Last>Singh</Last>
		</Name>
		<Credential>
			<Id>ssingh</Id>
			<Password Encryption="No">pass10</Password>
		</Credential>
		<Phone>
			<Work>4804103527</Work>
			<Cell>4804103527</Cell>
		</Phone>
		<Category>Friend</Category>
	</Person>
	<Person>
		<Name>
			<First>Rashik</First>
			<Last>Kotwal</Last>
		</Name>
		<Credential>
			<Id>rkotwal</Id>
			<Password Encryption="Yes">pass11</Password>
		</Credential>
		<Phone>
			<Work>4804103528</Work>
			<Cell Provider="IDEA">4804103528</Cell>
		</Phone>
		<Category>Family</Category>
	</Person>
	<Person>
		<Name>
			<First>Tara</First>
			<Last>Kailveer</Last>
		</Name>
		<Credential>
			<Id>tkaliveer</Id>
			<Password Encryption="No">pass12</Password>
		</Credential>
		<Phone>
			<Work>4804103529</Work>
			<Cell Provider="VODA">4804103529</Cell>
		</Phone>
		<Category>Work</Category>
	</Person>
	<Person>
		<Name>
			<First>Priya</First>
			<Last>Nair</Last>
		</Name>
		<Credential>
			<Id>pnair</Id>
			<Password Encryption="Yes">pass13</Password>
		</Credential>
		<Phone>
			<Work>4804103530</Work>
			<Cell Provider="ATT">4804103530</Cell>
		</Phone>
		<Category>Friend</Category>
	</Person>
	<Person>
		<Name>
			<First>Thara</First>
			<Last>Kn</Last>
		</Name>
		<Credential>
			<Id>thara</Id>
			<Password Encryption="No">pass14</Password>
		</Credential>
		<Phone>
			<Work>4804103531</Work>
			<Cell Provider="Verizon">4804103531</Cell>
		</Phone>
		<Category>Family</Category>
	</Person>
	<Person>
		<Name>
			<First>Nagashree</First>
			<Last>Venugopal</Last>
		</Name>
		<Credential>
			<Id>nvenu</Id>
			<Password Encryption="Yes">pass15</Password>
		</Credential>
		<Phone>
			<Work>4804103531</Work>
			<Cell Provider="Reliance">4804103531</Cell>
		</Phone>
		<Category>Work</Category>
	</Person>
</Persons>
